log_level = "info"
local_storage = 'test_data/local_storage'

[install]
user_path = 'test_data/user_bin'
system_path = 'test_data/system_bin'

[build]
default_environment = "container"

[repositories.main]
url = "http://github.com/mattslaney/sourcery-repository.git"
branch = "main" 
priority = 10

[repositories.wip]
url = "http://github.com/mattslaney/sourcery-repository.git"
branch = "wip"
priority = 20

